#cloud-config
package_update: true
packages:
  - figlet
  - unzip
  - dnsutils
  - curl
  - git
  - telnet
  - vim

runcmd:
  - sed -i -e '/^Port/s/^.*$/Port 4444/' etc/ssh/sshd_config
  - service ssh restart
  - sudo apt update  
  - cd /usr/local && wget https://telescope-eu-west-0.oss.eu-west-0.prod-cloud-ocb.orange-business.com/scripts/agentInstall.sh && chmod 755 agentInstall.sh && ./agentInstall.sh
  - wget --no-check-certificate 'https://hss-agent.oss.eu-west-0.prod-cloud-ocb.orange-business.com/linux/HwAgentInstall_64.sh' && chmod +x HwAgentInstall_64.sh && ./HwAgentInstall_64.sh
  - curl http://icagent-eu-west-0.oss.eu-west-0.prod-cloud-ocb.orange-business.com/ICAgent_linux/apm_agent_install.sh > apm_agent_install.sh && REGION=eu-west-0 bash apm_agent_install.sh -accessip 100.125.0.94 -obsdomain oss.eu-west-0.prod-cloud-ocb.orange-business.com;
 # - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
 # - curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
 # - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
 # - source <(kubectl completion bash)
 # - echo "source <(kubectl completion bash)" >> ~/.bashrc
 # - alias k=kubectl
 # - complete -o default -F __start_kubectl k
 # - mkdir -p $HOME/.kube
 # - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
 # - chmod 700 get_helm.sh
 # - ./get_helm.sh
 #  - sudo apt install apt-transport-https ca-certificates curl software-properties-common
 #  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
 #  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
 #  - apt-cache policy docker-ce
 # - sudo apt install docker-ce